language: node_js
node_js:
  - "5"

cache:
  directories:
    - node_modules

before_install:
  - rvm install 2
  - gem install sass

install:
  - npm install --only=dev
  - npm install node-sass -g

script:
  - npm test
  - node-sass --include-path styles styles/_coop-toolkit.scss > /dev/null
  - sass styles/_coop-toolkit.scss > /dev/null
